### ISSUE TITLE
possible to edit / change pe resource ?

### ISSUE THREAD

**Issue by eix128** [dorkbox/PeParser#1]
hi , i want to change my jpg images or strings inside my exe.
is it possible to find and change resource string or binary , images ?
if yes , is there any sample for that?

**Comment by dorkbox** [comment]
Changing a PE file would be something you would have to implement. While most of the data structure definitions in place (you wouldn't be starting from zero) -- it would be a lot of work.  

Off the top of my head, http://www.resedit.net/ might do what you need.

**Comment by eix128** [comment]
but i need solution for java.
i will implement it inside my opengl project

**Comment by dorkbox** [comment]
If you implement writing/editing PE files, I will gladly include your work in this project.
